/**
 * @file tkl_system.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "gd32vw55x.h"
#include "tkl_system.h"
#include "tuya_error_code.h"
#include "wrapper_os.h"
// --- END: user defines and implements ---

#ifdef TUYAOS_SUPPORT
/**
* @brief system reset
*
* @param none
*
* @return none
*/
VOID_T tkl_system_reset(VOID_T)
{
    // --- BEGIN: user implements ---
    SysTimer_SoftwareReset();
    return ;
    // --- END: user implements ---
}

/**
* @brief Get system tick count
*
* @param none
*
* @return system tick count
*/
SYS_TICK_T tkl_system_get_tick_count(VOID_T)
{
    // --- BEGIN: user implements ---
    return sys_os_now(FALSE);
    // --- END: user implements ---
}

/**
* @brief Get system millisecond
*
* @param none
*
* @return system millisecond
*/
SYS_TIME_T tkl_system_get_millisecond(VOID_T)
{
    // --- BEGIN: user implements ---
    return sys_time_get(NULL);
    // --- END: user implements ---
}

/**
* @brief Get system random data
*
* @param[in] range: random from 0  to range
*
* @return random value
*/
INT_T tkl_system_get_random(UINT_T range)
{
    // --- BEGIN: user implements ---
    UINT_T random_data = 0;

    if (!sys_random_bytes_get(&random_data, 4)) {
        return random_data % range;
    } else {
        return OPRT_COM_ERROR;
    }

    // --- END: user implements ---
}

/**
* @brief Get system reset reason
*
* @param[in] describe: point to reset reason describe
*
* @return reset reason
*/
TUYA_RESET_REASON_E tkl_system_get_reset_reason(CHAR_T** describe)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
* @brief  system sleep
*
* @param[in] describe: num ms
*
* @return none
*/
VOID_T tkl_system_sleep(UINT_T num_ms)
{
    // --- BEGIN: user implements ---
    sys_ms_sleep(num_ms);
    return ;
    // --- END: user implements ---
}

/**
* @brief system delay
*
* @param[in] msTime: time in MS
*
* @note This API is used for system sleep.
*
* @return VOID
*/
VOID_T tkl_system_delay(UINT_T num_ms)
{
    // --- BEGIN: user implements ---
    sys_ms_sleep(num_ms * OS_MS_PER_TICK);
    return ;
    // --- END: user implements ---
}

/**
* @brief get system cpu info
*
* @param[in] cpu_ary: info of cpus
* @param[in] cpu_cnt: num of cpu
* @note This API is used for system cpu info get.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/

OPERATE_RET tkl_system_get_cpu_info(TUYA_CPU_INFO_T **cpu_ary, INT_T *cpu_cnt)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

#endif /* TUYAOS_SUPPORT */
