################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/aes-cbc.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/dh_group5.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/dh_groups.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/rsn_supp/preauth.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/utils/uuid.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_attr_build.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_attr_parse.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_attr_process.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_common.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_dev_attr.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_enrollee.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_registrar.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/wpa_supplicant/wps_supplicant.c 

C_DEPS += \
./wpa_supplicant/wps/aes-cbc.d \
./wpa_supplicant/wps/dh_group5.d \
./wpa_supplicant/wps/dh_groups.d \
./wpa_supplicant/wps/preauth.d \
./wpa_supplicant/wps/uuid.d \
./wpa_supplicant/wps/wps.d \
./wpa_supplicant/wps/wps_attr_build.d \
./wpa_supplicant/wps/wps_attr_parse.d \
./wpa_supplicant/wps/wps_attr_process.d \
./wpa_supplicant/wps/wps_common.d \
./wpa_supplicant/wps/wps_dev_attr.d \
./wpa_supplicant/wps/wps_enrollee.d \
./wpa_supplicant/wps/wps_registrar.d \
./wpa_supplicant/wps/wps_supplicant.d 

OBJS += \
./wpa_supplicant/wps/aes-cbc.o \
./wpa_supplicant/wps/dh_group5.o \
./wpa_supplicant/wps/dh_groups.o \
./wpa_supplicant/wps/preauth.o \
./wpa_supplicant/wps/uuid.o \
./wpa_supplicant/wps/wps.o \
./wpa_supplicant/wps/wps_attr_build.o \
./wpa_supplicant/wps/wps_attr_parse.o \
./wpa_supplicant/wps/wps_attr_process.o \
./wpa_supplicant/wps/wps_common.o \
./wpa_supplicant/wps/wps_dev_attr.o \
./wpa_supplicant/wps/wps_enrollee.o \
./wpa_supplicant/wps/wps_registrar.o \
./wpa_supplicant/wps/wps_supplicant.o 


# Each subdirectory must supply rules for building sources it contributes
wpa_supplicant/wps/aes-cbc.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/aes-cbc.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/dh_group5.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/dh_group5.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/dh_groups.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/dh_groups.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/preauth.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/rsn_supp/preauth.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/uuid.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/utils/uuid.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_attr_build.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_attr_build.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_attr_parse.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_attr_parse.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_attr_process.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_attr_process.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_common.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_common.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_dev_attr.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_dev_attr.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_enrollee.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_enrollee.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_registrar.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/wps/wps_registrar.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/wps/wps_supplicant.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/wpa_supplicant/wps_supplicant.c wpa_supplicant/wps/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-wpa_supplicant-2f-wps

clean-wpa_supplicant-2f-wps:
	-$(RM) ./wpa_supplicant/wps/aes-cbc.d ./wpa_supplicant/wps/aes-cbc.o ./wpa_supplicant/wps/dh_group5.d ./wpa_supplicant/wps/dh_group5.o ./wpa_supplicant/wps/dh_groups.d ./wpa_supplicant/wps/dh_groups.o ./wpa_supplicant/wps/preauth.d ./wpa_supplicant/wps/preauth.o ./wpa_supplicant/wps/uuid.d ./wpa_supplicant/wps/uuid.o ./wpa_supplicant/wps/wps.d ./wpa_supplicant/wps/wps.o ./wpa_supplicant/wps/wps_attr_build.d ./wpa_supplicant/wps/wps_attr_build.o ./wpa_supplicant/wps/wps_attr_parse.d ./wpa_supplicant/wps/wps_attr_parse.o ./wpa_supplicant/wps/wps_attr_process.d ./wpa_supplicant/wps/wps_attr_process.o ./wpa_supplicant/wps/wps_common.d ./wpa_supplicant/wps/wps_common.o ./wpa_supplicant/wps/wps_dev_attr.d ./wpa_supplicant/wps/wps_dev_attr.o ./wpa_supplicant/wps/wps_enrollee.d ./wpa_supplicant/wps/wps_enrollee.o ./wpa_supplicant/wps/wps_registrar.d ./wpa_supplicant/wps/wps_registrar.o ./wpa_supplicant/wps/wps_supplicant.d ./wpa_supplicant/wps/wps_supplicant.o

.PHONY: clean-wpa_supplicant-2f-wps

