################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/bignum.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal-cipher.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal-modexp.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal-rsa.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/des-internal.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/eap_peer/eap_tls.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/eap_peer/eap_tls_common.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/pkcs1.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/pkcs5.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/pkcs8.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/rsa.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/sha1-tlsprf.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/sha256-tlsprf.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/tls_internal.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client_ocsp.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client_read.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client_write.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_common.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_cred.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_record.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/x509v3.c 

C_DEPS += \
./wpa_supplicant/tls/bignum.d \
./wpa_supplicant/tls/crypto_internal-cipher.d \
./wpa_supplicant/tls/crypto_internal-modexp.d \
./wpa_supplicant/tls/crypto_internal-rsa.d \
./wpa_supplicant/tls/crypto_internal.d \
./wpa_supplicant/tls/des-internal.d \
./wpa_supplicant/tls/eap_tls.d \
./wpa_supplicant/tls/eap_tls_common.d \
./wpa_supplicant/tls/pkcs1.d \
./wpa_supplicant/tls/pkcs5.d \
./wpa_supplicant/tls/pkcs8.d \
./wpa_supplicant/tls/rsa.d \
./wpa_supplicant/tls/sha1-tlsprf.d \
./wpa_supplicant/tls/sha256-tlsprf.d \
./wpa_supplicant/tls/tls_internal.d \
./wpa_supplicant/tls/tlsv1_client.d \
./wpa_supplicant/tls/tlsv1_client_ocsp.d \
./wpa_supplicant/tls/tlsv1_client_read.d \
./wpa_supplicant/tls/tlsv1_client_write.d \
./wpa_supplicant/tls/tlsv1_common.d \
./wpa_supplicant/tls/tlsv1_cred.d \
./wpa_supplicant/tls/tlsv1_record.d \
./wpa_supplicant/tls/x509v3.d 

OBJS += \
./wpa_supplicant/tls/bignum.o \
./wpa_supplicant/tls/crypto_internal-cipher.o \
./wpa_supplicant/tls/crypto_internal-modexp.o \
./wpa_supplicant/tls/crypto_internal-rsa.o \
./wpa_supplicant/tls/crypto_internal.o \
./wpa_supplicant/tls/des-internal.o \
./wpa_supplicant/tls/eap_tls.o \
./wpa_supplicant/tls/eap_tls_common.o \
./wpa_supplicant/tls/pkcs1.o \
./wpa_supplicant/tls/pkcs5.o \
./wpa_supplicant/tls/pkcs8.o \
./wpa_supplicant/tls/rsa.o \
./wpa_supplicant/tls/sha1-tlsprf.o \
./wpa_supplicant/tls/sha256-tlsprf.o \
./wpa_supplicant/tls/tls_internal.o \
./wpa_supplicant/tls/tlsv1_client.o \
./wpa_supplicant/tls/tlsv1_client_ocsp.o \
./wpa_supplicant/tls/tlsv1_client_read.o \
./wpa_supplicant/tls/tlsv1_client_write.o \
./wpa_supplicant/tls/tlsv1_common.o \
./wpa_supplicant/tls/tlsv1_cred.o \
./wpa_supplicant/tls/tlsv1_record.o \
./wpa_supplicant/tls/x509v3.o 


# Each subdirectory must supply rules for building sources it contributes
wpa_supplicant/tls/bignum.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/bignum.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/crypto_internal-cipher.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal-cipher.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/crypto_internal-modexp.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal-modexp.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/crypto_internal-rsa.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal-rsa.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/crypto_internal.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/crypto_internal.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/des-internal.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/des-internal.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/eap_tls.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/eap_peer/eap_tls.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/eap_tls_common.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/eap_peer/eap_tls_common.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/pkcs1.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/pkcs1.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/pkcs5.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/pkcs5.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/pkcs8.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/pkcs8.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/rsa.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/rsa.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/sha1-tlsprf.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/sha1-tlsprf.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/sha256-tlsprf.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/sha256-tlsprf.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tls_internal.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/crypto/tls_internal.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_client.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_client_ocsp.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client_ocsp.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_client_read.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client_read.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_client_write.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_client_write.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_common.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_common.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_cred.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_cred.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/tlsv1_record.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/tlsv1_record.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/tls/x509v3.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/tls/x509v3.c wpa_supplicant/tls/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-wpa_supplicant-2f-tls

clean-wpa_supplicant-2f-tls:
	-$(RM) ./wpa_supplicant/tls/bignum.d ./wpa_supplicant/tls/bignum.o ./wpa_supplicant/tls/crypto_internal-cipher.d ./wpa_supplicant/tls/crypto_internal-cipher.o ./wpa_supplicant/tls/crypto_internal-modexp.d ./wpa_supplicant/tls/crypto_internal-modexp.o ./wpa_supplicant/tls/crypto_internal-rsa.d ./wpa_supplicant/tls/crypto_internal-rsa.o ./wpa_supplicant/tls/crypto_internal.d ./wpa_supplicant/tls/crypto_internal.o ./wpa_supplicant/tls/des-internal.d ./wpa_supplicant/tls/des-internal.o ./wpa_supplicant/tls/eap_tls.d ./wpa_supplicant/tls/eap_tls.o ./wpa_supplicant/tls/eap_tls_common.d ./wpa_supplicant/tls/eap_tls_common.o ./wpa_supplicant/tls/pkcs1.d ./wpa_supplicant/tls/pkcs1.o ./wpa_supplicant/tls/pkcs5.d ./wpa_supplicant/tls/pkcs5.o ./wpa_supplicant/tls/pkcs8.d ./wpa_supplicant/tls/pkcs8.o ./wpa_supplicant/tls/rsa.d ./wpa_supplicant/tls/rsa.o ./wpa_supplicant/tls/sha1-tlsprf.d ./wpa_supplicant/tls/sha1-tlsprf.o ./wpa_supplicant/tls/sha256-tlsprf.d ./wpa_supplicant/tls/sha256-tlsprf.o ./wpa_supplicant/tls/tls_internal.d ./wpa_supplicant/tls/tls_internal.o ./wpa_supplicant/tls/tlsv1_client.d ./wpa_supplicant/tls/tlsv1_client.o ./wpa_supplicant/tls/tlsv1_client_ocsp.d ./wpa_supplicant/tls/tlsv1_client_ocsp.o ./wpa_supplicant/tls/tlsv1_client_read.d ./wpa_supplicant/tls/tlsv1_client_read.o ./wpa_supplicant/tls/tlsv1_client_write.d ./wpa_supplicant/tls/tlsv1_client_write.o ./wpa_supplicant/tls/tlsv1_common.d ./wpa_supplicant/tls/tlsv1_common.o ./wpa_supplicant/tls/tlsv1_cred.d ./wpa_supplicant/tls/tlsv1_cred.o ./wpa_supplicant/tls/tlsv1_record.d ./wpa_supplicant/tls/tlsv1_record.o ./wpa_supplicant/tls/x509v3.d ./wpa_supplicant/tls/x509v3.o

.PHONY: clean-wpa_supplicant-2f-tls

