################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/wpa_supplicant/ap.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_config.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_drv_ops.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_list.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_mlme.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/beacon.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/bss_load.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/utils/crc32.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ctrl_iface_ap.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/drv_callbacks.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/eap_server/eap_server_methods.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/eap_user_db.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/hostapd.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/hw_features.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_auth.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_he.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_ht.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_shared.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_vht.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_1x.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/utils/ip_addr.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/mbo_ap.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/neighbor_db.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/pmksa_cache_auth.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/rrm.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/sta_info.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/tkip_countermeasures.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/utils.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wmm.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wpa_auth.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wpa_auth_glue.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wpa_auth_ie.c \
C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wps_hostapd.c 

C_DEPS += \
./wpa_supplicant/ap/ap.d \
./wpa_supplicant/ap/ap_config.d \
./wpa_supplicant/ap/ap_drv_ops.d \
./wpa_supplicant/ap/ap_list.d \
./wpa_supplicant/ap/ap_mlme.d \
./wpa_supplicant/ap/beacon.d \
./wpa_supplicant/ap/bss_load.d \
./wpa_supplicant/ap/crc32.d \
./wpa_supplicant/ap/ctrl_iface_ap.d \
./wpa_supplicant/ap/drv_callbacks.d \
./wpa_supplicant/ap/eap_server_methods.d \
./wpa_supplicant/ap/eap_user_db.d \
./wpa_supplicant/ap/hostapd.d \
./wpa_supplicant/ap/hw_features.d \
./wpa_supplicant/ap/ieee802_11.d \
./wpa_supplicant/ap/ieee802_11_auth.d \
./wpa_supplicant/ap/ieee802_11_he.d \
./wpa_supplicant/ap/ieee802_11_ht.d \
./wpa_supplicant/ap/ieee802_11_shared.d \
./wpa_supplicant/ap/ieee802_11_vht.d \
./wpa_supplicant/ap/ieee802_1x.d \
./wpa_supplicant/ap/ip_addr.d \
./wpa_supplicant/ap/mbo_ap.d \
./wpa_supplicant/ap/neighbor_db.d \
./wpa_supplicant/ap/pmksa_cache_auth.d \
./wpa_supplicant/ap/rrm.d \
./wpa_supplicant/ap/sta_info.d \
./wpa_supplicant/ap/tkip_countermeasures.d \
./wpa_supplicant/ap/utils.d \
./wpa_supplicant/ap/wmm.d \
./wpa_supplicant/ap/wpa_auth.d \
./wpa_supplicant/ap/wpa_auth_glue.d \
./wpa_supplicant/ap/wpa_auth_ie.d \
./wpa_supplicant/ap/wps_hostapd.d 

OBJS += \
./wpa_supplicant/ap/ap.o \
./wpa_supplicant/ap/ap_config.o \
./wpa_supplicant/ap/ap_drv_ops.o \
./wpa_supplicant/ap/ap_list.o \
./wpa_supplicant/ap/ap_mlme.o \
./wpa_supplicant/ap/beacon.o \
./wpa_supplicant/ap/bss_load.o \
./wpa_supplicant/ap/crc32.o \
./wpa_supplicant/ap/ctrl_iface_ap.o \
./wpa_supplicant/ap/drv_callbacks.o \
./wpa_supplicant/ap/eap_server_methods.o \
./wpa_supplicant/ap/eap_user_db.o \
./wpa_supplicant/ap/hostapd.o \
./wpa_supplicant/ap/hw_features.o \
./wpa_supplicant/ap/ieee802_11.o \
./wpa_supplicant/ap/ieee802_11_auth.o \
./wpa_supplicant/ap/ieee802_11_he.o \
./wpa_supplicant/ap/ieee802_11_ht.o \
./wpa_supplicant/ap/ieee802_11_shared.o \
./wpa_supplicant/ap/ieee802_11_vht.o \
./wpa_supplicant/ap/ieee802_1x.o \
./wpa_supplicant/ap/ip_addr.o \
./wpa_supplicant/ap/mbo_ap.o \
./wpa_supplicant/ap/neighbor_db.o \
./wpa_supplicant/ap/pmksa_cache_auth.o \
./wpa_supplicant/ap/rrm.o \
./wpa_supplicant/ap/sta_info.o \
./wpa_supplicant/ap/tkip_countermeasures.o \
./wpa_supplicant/ap/utils.o \
./wpa_supplicant/ap/wmm.o \
./wpa_supplicant/ap/wpa_auth.o \
./wpa_supplicant/ap/wpa_auth_glue.o \
./wpa_supplicant/ap/wpa_auth_ie.o \
./wpa_supplicant/ap/wps_hostapd.o 


# Each subdirectory must supply rules for building sources it contributes
wpa_supplicant/ap/ap.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/wpa_supplicant/ap.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ap_config.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_config.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ap_drv_ops.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_drv_ops.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ap_list.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_list.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ap_mlme.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ap_mlme.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/beacon.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/beacon.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/bss_load.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/bss_load.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/crc32.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/utils/crc32.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ctrl_iface_ap.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ctrl_iface_ap.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/drv_callbacks.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/drv_callbacks.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/eap_server_methods.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/eap_server/eap_server_methods.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/eap_user_db.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/eap_user_db.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/hostapd.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/hostapd.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/hw_features.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/hw_features.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_11.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_11_auth.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_auth.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_11_he.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_he.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_11_ht.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_ht.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_11_shared.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_shared.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_11_vht.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_11_vht.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ieee802_1x.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/ieee802_1x.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/ip_addr.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/utils/ip_addr.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/mbo_ap.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/mbo_ap.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/neighbor_db.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/neighbor_db.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/pmksa_cache_auth.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/pmksa_cache_auth.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/rrm.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/rrm.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/sta_info.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/sta_info.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/tkip_countermeasures.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/tkip_countermeasures.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/utils.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/utils.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/wmm.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wmm.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/wpa_auth.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wpa_auth.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/wpa_auth_glue.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wpa_auth_glue.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/wpa_auth_ie.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wpa_auth_ie.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wpa_supplicant/ap/wps_hostapd.o: C:/Users/stapi/OneDrive/Desktop/GD32VW553/V1_MQTT_OK/GD32VW55X_Wifi_BLE_SDK/GD32VW55x_RELEASE_V1.0.2/MSDK/wpa_supplicant/src/ap/wps_hostapd.c wpa_supplicant/ap/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-label  -g -std=c99 -DCFG_RTOS -DCONFIG_WPA_SUPPLICANT -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\wpa_supplicant\wpa_supplicant" -I"..\..\..\..\wpa_supplicant\src" -I"..\..\..\..\wpa_supplicant\src\utils" -I"..\..\..\..\wpa_supplicant\src\crypto" -I"..\..\..\..\wpa_supplicant\src\wps" -I"..\..\..\..\wpa_supplicant\src\eap_common" -I"..\..\..\..\wpa_supplicant\src\eap_peer" -I"..\..\..\..\wpa_supplicant\src\eapol_supp" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\..\ROM-EXPORT\mbedtls-2.17.0-rom\include" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\util\include" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.1.2\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.1.2\port" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-wpa_supplicant-2f-ap

clean-wpa_supplicant-2f-ap:
	-$(RM) ./wpa_supplicant/ap/ap.d ./wpa_supplicant/ap/ap.o ./wpa_supplicant/ap/ap_config.d ./wpa_supplicant/ap/ap_config.o ./wpa_supplicant/ap/ap_drv_ops.d ./wpa_supplicant/ap/ap_drv_ops.o ./wpa_supplicant/ap/ap_list.d ./wpa_supplicant/ap/ap_list.o ./wpa_supplicant/ap/ap_mlme.d ./wpa_supplicant/ap/ap_mlme.o ./wpa_supplicant/ap/beacon.d ./wpa_supplicant/ap/beacon.o ./wpa_supplicant/ap/bss_load.d ./wpa_supplicant/ap/bss_load.o ./wpa_supplicant/ap/crc32.d ./wpa_supplicant/ap/crc32.o ./wpa_supplicant/ap/ctrl_iface_ap.d ./wpa_supplicant/ap/ctrl_iface_ap.o ./wpa_supplicant/ap/drv_callbacks.d ./wpa_supplicant/ap/drv_callbacks.o ./wpa_supplicant/ap/eap_server_methods.d ./wpa_supplicant/ap/eap_server_methods.o ./wpa_supplicant/ap/eap_user_db.d ./wpa_supplicant/ap/eap_user_db.o ./wpa_supplicant/ap/hostapd.d ./wpa_supplicant/ap/hostapd.o ./wpa_supplicant/ap/hw_features.d ./wpa_supplicant/ap/hw_features.o ./wpa_supplicant/ap/ieee802_11.d ./wpa_supplicant/ap/ieee802_11.o ./wpa_supplicant/ap/ieee802_11_auth.d ./wpa_supplicant/ap/ieee802_11_auth.o ./wpa_supplicant/ap/ieee802_11_he.d ./wpa_supplicant/ap/ieee802_11_he.o ./wpa_supplicant/ap/ieee802_11_ht.d ./wpa_supplicant/ap/ieee802_11_ht.o ./wpa_supplicant/ap/ieee802_11_shared.d ./wpa_supplicant/ap/ieee802_11_shared.o ./wpa_supplicant/ap/ieee802_11_vht.d ./wpa_supplicant/ap/ieee802_11_vht.o ./wpa_supplicant/ap/ieee802_1x.d ./wpa_supplicant/ap/ieee802_1x.o ./wpa_supplicant/ap/ip_addr.d ./wpa_supplicant/ap/ip_addr.o ./wpa_supplicant/ap/mbo_ap.d ./wpa_supplicant/ap/mbo_ap.o ./wpa_supplicant/ap/neighbor_db.d ./wpa_supplicant/ap/neighbor_db.o ./wpa_supplicant/ap/pmksa_cache_auth.d ./wpa_supplicant/ap/pmksa_cache_auth.o ./wpa_supplicant/ap/rrm.d ./wpa_supplicant/ap/rrm.o ./wpa_supplicant/ap/sta_info.d ./wpa_supplicant/ap/sta_info.o ./wpa_supplicant/ap/tkip_countermeasures.d ./wpa_supplicant/ap/tkip_countermeasures.o ./wpa_supplicant/ap/utils.d ./wpa_supplicant/ap/utils.o ./wpa_supplicant/ap/wmm.d ./wpa_supplicant/ap/wmm.o ./wpa_supplicant/ap/wpa_auth.d ./wpa_supplicant/ap/wpa_auth.o ./wpa_supplicant/ap/wpa_auth_glue.d ./wpa_supplicant/ap/wpa_auth_glue.o ./wpa_supplicant/ap/wpa_auth_ie.d ./wpa_supplicant/ap/wpa_auth_ie.o ./wpa_supplicant/ap/wps_hostapd.d ./wpa_supplicant/ap/wps_hostapd.o

.PHONY: clean-wpa_supplicant-2f-ap

